### PR TITLE
run `gcloud services enable container.googleapis.com` in tools/init.sh

### LINKED ISSUE #787: automatically run `gcloud services enable container.googleapis.com`
When I executed `tools/start.sh`, the error below occurred.
That's because I haven't enabled container.googleapis.com.
How about running `gcloud services enable container.googleapis.com` in the script?
Do you think it's better to leave it to users?

```
$ ./tools/start.sh
（snip）
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=403, message=Kubernetes Engine API is not enabled for this project. Please ensure it is enabled in Google Cloud Console and try again: visit https://console.cloud.google.com/apis/api/container.googleapis.com/overview?project=kubernetes-native-testbed to do so.
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/kubernetes-native-testbed/locations/asia-northeast1/clusters/testbed.
No cluster named 'testbed' in kubernetes-native-testbed.
```

### PR DESCRIPTION
**Pull request by oke-py**
fixes #787

### CODE REVIEW

File: tools/init.sh [hunk 1]
```diff
@@ -6,6 +6,6 @@ CURRENT_DIR=$(cd $(dirname $0); pwd)
 source ${CURRENT_DIR}/env
 
 ${CURRENT_DIR}/init_cli.sh
+${CURRENT_DIR}/enable_service.sh
```
Comment (MasayaAoyama) [inline tools/init.sh]: can you change script name more generic.
e.g. init_cloudprovider.sh, prepare_cloud.sh and so on.

**Review by MasayaAoyama — CHANGES_REQUESTED** [review]

File: tools/init.sh (hunk 1 above)
Comment (oke-py) [reply tools/init.sh]: OK, done.

**Comment by MasayaAoyama** [comment]
@oke-py Thanks a lot!
LGTM
